name: "PHP-CS-Fixer"

on:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  phpunit-tests:
    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.2','8.3']
        
    name: PHPUnit (PHP ${{ matrix.php_versions }})
    runs-on: ubuntu-latest
    steps:
      - name: add safe directory
        run: git config --global --add safe.directory /app

      - name: install php ${{ matrix.php_versions }} with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          extensions: json ctype openssl ssh2 gd
          coverage: none
          tools: none
    
      - name: checkout repository
        uses: actions/checkout@v4.2.1
          
      - name: install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          php_version: ${{ matrix.php_versions }}
          php_extensions: json ctype openssl ssh2 gd

      - name: run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --diff --dry-run
